{% set version = "0.2.0" %}

package:
  name: ruamel.yaml.clib
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/r/ruamel.yaml.clib/ruamel.yaml.clib-{{ version }}.tar.gz
  sha256: b66832ea8077d9b3f6e311c4a53d06273db5dc2db6e8a908550f3c14d67e718c

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python

test:
  requires:
    - ruamel.yaml
  imports:
    - _ruamel_yaml

about:
  home: https://bitbucket.org/ruamel/yaml.clib
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "C version of reader, parser and emitter for ruamel.yaml derived from libyaml"

extra:
  recipe-maintainers:
    - ocefpaf
