travis:
  secure:
    BINSTAR_TOKEN: eDQk/xvygMKczyvnYdqp83soco0XqVjErF3z2IG++Xljp66s5ewoRIiUmuLOKo5RfNbfSWcGL7RQO8dFOEc1VwhbFP9JHmp0mojohZbbeabDzqQLMaijUEYWmL7JMfPyDCqi7yVGa2w1gQnCwTTWNEJSqU/FZleIJkz6BHkaKK7wGSbUKpI9I7yx1S6RMvBWnDsacTqhrS0gAkb7fr7bujjvECBIA/TWza8nzvWeqXWdYv/n4BZqsTjInLINYbpdfUB8QgYzVVraVk0VqOe4fgV8AD4Yfuc2d8awwchoUxATgfEHMP5hjgEgTPpFHAtif7dD3/NgYcKG/lrgjsiW8GusUpuPXm/emolHNNH4wxIuZUHmPc3q/xj2hTiBQDEt9oGOXdgOGCUYjo+ZDwCRKaT8yav0TsViL3aNO0ngAostqqlbdwRye6VyqbqgrxrFAd7LgXoPHMx2OZwMayUs1S8nwft0ZU+pRP4lD1yiyQXvv4rDCsY0m/u4uwaQswM1uRbvkvHhaSvgX8d84LhNvMrHykd6+evkW05OmXkH74Ald4jelMAymRyo6P+2umNR3o4FLnBxvyCComKfHUr5FJiHZzIdZ+IdKXfeva42H6LxjfTMM79WHaBomwANh+NRmlHhrtay0NrB91/aaEZRQLNNBXQgiDWyBvt99Lj7B94=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
